FROM conda/miniconda3-centos7:latest
# Steps to create the docker image in the gitlab server(coelho)
# Copy this file to a root access directory
# cd to that directory
# sudo docker build -t cc_image .
RUN  yum install -y gcc g++ gcc-c++ cmake gfortran gcc-gfortran make
