from .task_web_pubchem import Pubchem
from .task_web_molinfo import MolecularInfo
from .task_web_showtargets import ShowTargets
from .task_web_coordinates import Coordinates
from .task_web_projections import Projections
from .task_web_plots import Plots
from .task_web_libraries import Libraries
from .task_web_similars import Similars
from .task_web_statsplots import StatsPlots
