
    --
    -- PostgreSQL database dump
    --

    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;

    SET default_tablespace = '';

    COPY public.similars (inchikey, version, explore_data) FROM stdin;
        AAAAEENPAALFRN-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAAZQPHATYWOK-JXMROGBWSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAABHMIRDIOYOK-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAABMNXUOFPYQK-GRMLSQNXSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAABTPAECTZDET-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAACBXVBBDAYRQ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAACGYYPWMUUFL-LJQANCHMSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADBGOEWPPOQQ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADCKOTKJSVMJ-SZNDQCEHSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADJKPSAGHJNF-MKICQXMISA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADKYXUTOBAGS-XCBNKYQSSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADMRIIAVPPNA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADPBLPXCELKR-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADQEFQWNJHOZ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAADXMXYZRUUBD-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAFCIOIVLBHKA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAFJOVTHDHBBR-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAFNFZYVYYALD-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAFZMYJJHWUPN-SOOFDHNKSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAFZMYJJHWUPN-TXICZTDVSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAGFCUDAXPDAA-CIQZPUONSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAGJRIQWZJWDJ-FQEVSTJZSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAHKMSAPZHJEC-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAHTCZONLHYSA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAHTJUBISKQEG-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAIGLFCNVJIAZ-DOVGANMCSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAJOLVNKDABOE-CJNGLKHVSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAJOLVNKDABOE-CZUORRHYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAKBEWYWAMEEW-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAKPBKWFMPTSQ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAALVBIWOWZUBR-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAALVYBICLMAMA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAALWAVFSMSWAR-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAMDLDGBNPDEO-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAMHEXGLYVZSJ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAMJICHKUQUOZ-DVKNGEFBSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAMTKOLGCYPPA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAMYWMNTPTTKE-ABKXIKBNSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAMYWMNTPTTKE-JDNHERCYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAANFBRBVCTCKW-MRXNPFEDSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAANLCCSPMLHMI-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAOTGDHZDZLFN-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAPQZDYNWUVQA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAPTRVNSYQELA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAQFGUYHFJNHI-SFHVURJKSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAQIVSZQLECHP-BJKOFHAPSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAQIVSZQLECHP-DNQXCXABSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAQKTZKLRYKHR-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAQLZGRRWOOHU-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAQLZOAUALGQJ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAARKAYZOWLPBX-UKTHLTGXSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAARORKNKJOILL-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAARUSQRQGITCF-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAASNKNLMQBKFV-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAASRNHSMGFXGC-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAUCJJEASDVLN-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAVVDAKZZKRGS-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAWKNFGNGANRE-UKILVPOCSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAWRDCWFBVNLC-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAWSHDPPHCEMX-XNTDXEJSSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAXBDFZRXKRPL-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAXQCAHTZSFCV-CLLDFNAGSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAYSHMCBYUFIR-MFOYZWKCSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAZRMGPBSWFDK-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAZUNCZBZHDPM-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AAAZZMUJUOJDHZ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABBDWBDIORMPG-GOTSBHOMSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABBLHFMQYNECK-NRFANRHFSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABBVPSPFWBHMR-HNNXBMFYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABBVPSPFWBHMR-OAHLLOKOSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABBVPSPFWBHMR-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABBWGRBUNATRS-QGPRMEMTSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABCJBBNSYLDFX-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABCWKAVZKTWQL-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABDLAPZJNSXOU-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABDPJPJDYYAFN-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABDRJHZBVPFLI-KHPPLWFESA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABFBZYCIQMNMX-WLHASUIJSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABFMIZVFWENJZ-UNMCSNQZSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABFQPXMRIEYFI-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABFYZQNRNFYNF-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABGBLWHWAZOHL-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABGHFWXMGZNOV-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABHAFTYFDHGCT-LBPRGKRZSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABHHGUROUXKFW-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABHMQVNLULEDP-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABHPMAMDHAYRG-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABHSZUTAUSICN-HZJYTTRNSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABIHRPKNRHYNW-FUHWJXTLSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABIMOFMGWOKOP-WQANXHIZSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABIUXXJGLXQTM-KQFVITFDSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABIUXXJGLXQTM-MBEDZMRZSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABJEMQLIHBZAW-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABJFGNYJCCAEA-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABJMUMRLMCEIF-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABLJASYIDRGBU-GUTACTQSSA-M	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABLMOXKAOXTGJ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABLNHSZFIPOBJ-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABLPEAJBJZTBF-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
AABLQBRGBFMNIT-UHFFFAOYSA-N	2024_02	{"LINCS compounds": [], "Experimental drugs": [], "Tool compounds": [], "Prestwick chemical library": [], "Human metabolites": [], "NIH clinical collection": [], "Approved drugs": [], "All Bioactive Molecules": [], "Tradicional Chinese medicines": [], "NCI diversity collection": []}
\.
